# Simple workflow for deploying static content to GitHub Pages
name: Admin Teamsbuilders

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret in a Step
        run: echo ${{ secrets.MY_SECRET_KEY }}

  deploy:
   needs: [my_job]
   runs-on: ubuntu-latest

   steps: 
    - name: SSH Deploy
      uses: ubuntu-boy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sh /var/www/sh-test/deployment_admin.sh
